"""Initial

Revision ID: 0fa972dd8f79
Revises: 
Create Date: 2023-09-06 21:20:36.339856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa972dd8f79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('books',
        sa.Column('Id', sa.INTEGER(), nullable=False),
        sa.Column('Title', sa.String(), nullable=True),
        sa.Column('Author', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
