"""add user table 

Revision ID: 2c25e0e96fa5
Revises: 8b444e4e4446
Create Date: 2023-10-03 17:54:24.361472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c25e0e96fa5'
down_revision: Union[str, None] = '8b444e4e4446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.String(length=120), nullable=True),
    sa.Column('Color', sa.Enum('Pink', 'Black', 'White', 'Yellow', name='colorenum'), nullable=False),
    sa.Column('Size', sa.Enum('XS', 'S', 'M', 'L', 'Xl', 'XXL', name='sizeenum'), nullable=False),
    sa.Column('Photo_Url', sa.String(length=255), nullable=True),
    sa.Column('CreatedDate_At', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('LastModified_At', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('users',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('FullName', sa.String(length=120), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=13), nullable=True),
    sa.Column('CreatedDate_At', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('LastModified_At', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('FullName')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('clothes')
    # ### end Alembic commands ###
