"""add readers

Revision ID: 2e8ce7948c8b
Revises: e3fd541258aa
Create Date: 2023-09-06 21:51:50.599232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8ce7948c8b'
down_revision: Union[str, None] = 'e3fd541258aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('LastName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.add_column('books', sa.Column('ReaderId', sa.INTEGER(), nullable=False))
    op.create_index(op.f('ix_books_ReaderId'), 'books', ['ReaderId'], unique=False)
    op.create_foreign_key(None, 'books', 'readers', ['ReaderId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_ReaderId'), table_name='books')
    op.drop_column('books', 'ReaderId')
    op.drop_table('readers')
    # ### end Alembic commands ###
