"""Initial

Revision ID: e3fd541258aa
Revises: 0fa972dd8f79
Create Date: 2023-09-06 21:36:56.580223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fd541258aa'
down_revision: Union[str, None] = '0fa972dd8f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('Pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'Pages')
    # ### end Alembic commands ###
